# Sample Project Configuration
# PROMETHEUS Project-based AI Agent Factory

metadata:
  name: "sample_project"
  description: "샘플 프로젝트 - PROMETHEUS 기능 테스트"
  version: "1.0.0"
  author: "PROMETHEUS"
  tags:
    - sample
    - demo
    - test

# 기본 LLM 설정
default_llm:
  provider: "openai"
  model: "gpt-4-turbo-preview"
  temperature: 0.7
  max_tokens: 4096
  api_key_env: "OPENAI_API_KEY"

# Agent 설정
agents:
  - agent_type: "planner"
    name: "ProjectPlanner"
    tools:
      - "python_exec"
    system_prompt: |
      당신은 프로젝트 계획을 수립하는 전문 AI입니다.
      사용자의 요청을 분석하고 실행 가능한 단계로 분해합니다.

  - agent_type: "executor"
    name: "TaskExecutor"
    tools:
      - "python_exec"
      - "desktop_commander_safe"
    system_prompt: |
      당신은 계획된 작업을 실행하는 AI입니다.
      주어진 도구를 활용하여 작업을 수행합니다.

  - agent_type: "writer"
    name: "DocumentWriter"
    tools: []
    system_prompt: |
      당신은 문서 작성 전문 AI입니다.
      실행 결과를 바탕으로 명확하고 체계적인 문서를 작성합니다.

  - agent_type: "qa"
    name: "QualityAssurance"
    tools: []
    system_prompt: |
      당신은 품질 검증 전문 AI입니다.
      결과물의 품질을 검토하고 개선점을 제안합니다.

# Tool 설정
tools:
  - name: "python_exec"
    enabled: true
    config:
      timeout: 30
      sandbox_enabled: true

  - name: "paper_rag"
    enabled: false
    config:
      top_k: 5

  - name: "desktop_commander_safe"
    enabled: true
    config:
      allowed_commands:
        - "read_file"
        - "list_dir"
        - "search"
      allowed_directories:
        - "./projects"
        - "./templates"

# 메모리 설정
memory:
  type: "local"
  vector_store: "chroma"
  persist_path: "./data/memory"
  max_context_length: 4096

# 추가 설정
settings:
  enable_tracing: true
  log_level: "INFO"
  max_iterations: 10
